---
title: "Tables convergence trait profiles - RF models summary"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Paper/Tables/") })
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE}
# Set up
library(data.table)
library(dplyr)
library(reactable)
library(htmltools)
```

# Random forest models

## Table 8

Multi-category brier (mBrier) score of the test and training data for the fitted random forest models.

```{r, echo = FALSE}
brier_scores <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/perf_summary.rds")

reactable(
  brier_scores[, .(
    continent,
    mbrier_score_test = round(mbrier_score_test, digits = 2),
    mbrier_score_train = round(mbrier_score_train, digits = 2)
  )],
  columns = list(
    continent = colDef(name = "Continent",
                       width = 120),
    mbrier_score_test = colDef(name = "mBrier score test data"),
    mbrier_score_train = colDef(name = "mBrier score training data")
  )
)

```

```{r, echo = FALSE}

# summary_cr_taxa <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/Cache_comparison_climatic_reg/summary_cr_taxa.rds")
# 
# reactable(
#   summary_cr_taxa,
#   highlight = TRUE,
#   columns = list(
#     `Nr. Taxa EU` = colDef(name = "Nr. Taxa EU (mostly species lvl)"),
#     `Nr. Taxa NOA` = colDef(name = "Nr. Taxa NOA (genus lvl)")
#   ))
```