---
title: "Tables convergence trait profiles"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Paper/Tables/") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
# Set up
library(data.table)
library(reactable)
library(htmltools)
```

## Table 2:
Contribution of grouping features to the global distances.

```{r, echo = FALSE}
# Load data global distances
global_dist <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/global_dist.rds")
global_dist <- rbindlist(global_dist, idcol = "continent")

reactable(global_dist[, .(continent, grouping_feature, global_dist = round(`global distance`, digits = 2))],
          columns = list(continent = colDef(name = "Continent"), 
                         grouping_feature = colDef(name = "Grouping feature"),
                         global_dist = colDef(name = "Correlation with total distance",
                                              align = "center")), 
          filterable = TRUE,
          highlight = TRUE)
```



## Table 3: 
Most important traits according to the permutation importance from the random forest models and according to the selection by the Boruta algorithm.

```{r, echo = FALSE}
# TODO whole boruta for SI

# rf permutation importance
most_imp_vars <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/most_imp_vars.rds")

continents <- sub("([A-Z]{2,})(\\.)(.+)", "\\1", rownames(most_imp_vars))
most_imp_vars$continents <- continents
most_imp_vars$traits <- rownames(most_imp_vars)
setDT(most_imp_vars)
most_imp_vars[, traits := sub("([A-Z]{2,})(\\.)(.+)", "\\3", traits)]
miv_pub <-
  most_imp_vars[order(continents, -y), .(pi_score = head(y, n = 5),
                                         traits_perm_imp = head(traits, n = 5)),
                by = continents] 

# boruta
boruta_res <-
  readRDS(
    "/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/boruta_res.rds"
  )
boruta_res <- do.call(rbind, boruta_res)
continents <- sub("([A-Z]{2,})(\\.)(.+)", "\\1", rownames(boruta_res))
boruta_res$continents <- continents
boruta_res$traits <- rownames(boruta_res)
setDT(boruta_res)
boruta_res[, traits_boruta := sub("([A-Z]{2,})(\\.)(.+)", "\\3", traits)]
boruta_res <- boruta_res[order(continents, -meanImp), ]

miv_boruta <- boruta_res[, .(traits_boruta = head(traits_boruta, n = 5)), by = continents]

reactable(
  miv_pub[, .(
    continents, 
    traits_perm_imp,
    traits_boruta = miv_boruta$traits_boruta
  )],
  columns = list(
    continents = colDef(name = "Continent",
                       width = 120),
    traits_perm_imp = colDef(name = "Most important traits permutation importance"),
    traits_boruta = colDef(name = "Most important traits Boruta")
  ),
  filterable = TRUE,
  highlight = TRUE
)

```

## Table 4:
Multi-category brier (mBrier) score of the test and training data for the fitted random forest models. 

```{r, echo = FALSE}
brier_scores <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/perf_summary.rds")

reactable(
  brier_scores[, .(
    continent,
    mbrier_score_test = round(mbrier_score_test, digits = 2),
    mbrier_score_train = round(mbrier_score_train, digits = 2)
  )],
  columns = list(
    continent = colDef(name = "Continent",
                       width = 120),
    mbrier_score_test = colDef(name = "mBrier score test data"),
    mbrier_score_train = colDef(name = "mBrier score training data")
  )
)

```


```{r, echo = FALSE}

# summary_cr_taxa <- readRDS("/home/kunzst/Dokumente/Projects/Trait_DB/Convergence-trait-profiles/Cache/Cache_comparison_climatic_reg/summary_cr_taxa.rds")
# 
# reactable(
#   summary_cr_taxa,
#   highlight = TRUE,
#   columns = list(
#     `Nr. Taxa EU` = colDef(name = "Nr. Taxa EU (mostly species lvl)"),
#     `Nr. Taxa NOA` = colDef(name = "Nr. Taxa NOA (genus lvl)")
#   ))
```
